let MasterCard = [
  {
    digitalCardData: {
      artUri:
        "https://sandbox.assets.vims.visa.com/vims/cardart/5af3734cca4e439e97f00e4474d82447_imageA@2x.png",
      status: "ACTIVE",
      descriptorName: "Visa",
    },
    maskedBillingAddress: {
      city: "*****",
      countryCode: "US",
      line1: "105*****",
      line2: null,
      line3: null,
      state: "CA",
      zip: "*****",
    },
    panBin: null,
    panExpirationMonth: "12",
    panExpirationYear: "2025",
    panLastFour: "0110",
    srcDigitalCardId: "cc7538575d03eae5a94f1bcdac911d01",
    paymentCardDescriptor: "visa",
  },
  {
    srcDigitalCardId: "WMXp_LfbQm66KhWMdslcqw000000000000US",
    panBin: "222300",
    panLastFour: "4586",
    digitalCardData: {
      descriptorName: "Test Bank 2",
      artUri:
        "https://sbx.assets.mastercard.com/card-art/combined-image-asset/42d31eae-9961-45b6-9fe3-76ad70a0a525.png",
      isCoBranded: false,
      status: "ACTIVE",
    },
    digitalCardFeatures: [],
    panExpirationMonth: "03",
    panExpirationYear: "2030",
    paymentCardDescriptor: "mastercard",
    paymentCardType: "DEBIT",
    maskedBillingAddress: {
      line1: "6*** S**** S********* D****",
      city: "Los Angeles",
      state: "CA",
      countryCode: "US",
      zip: "90056",
    },
    cardholderFirstName: "a*******",
    cardholderLastName: "c********",
    cardholderFullName: "a******* c********",
  },
  {
    srcDigitalCardId: "geHXpeEfQF256Qs4Fdamvg000000000000US",
    panBin: "518600",
    panLastFour: "9908",
    digitalCardData: {
      descriptorName: "Mastercard",
      artUri:
        "https://sbx.assets.mastercard.com/card-art/combined-image-asset/HIGH-MASK-3x.png",
      isCoBranded: false,
      status: "ACTIVE",
    },
    digitalCardFeatures: [],
    panExpirationMonth: "01",
    panExpirationYear: "2039",
    paymentCardDescriptor: "mastercard",
    paymentCardType: "PREPAID",
    maskedBillingAddress: {
      line1: "6*** S**** S********* D****",
      city: "Los Angeles",
      state: "CA",
      countryCode: "US",
      zip: "90056",
    },
    cardholderFirstName: "a*******",
    cardholderLastName: "c********",
    cardholderFullName: "a******* c********",
  },
  {
    srcDigitalCardId: "uCwj2iwDR0izPxOQuJHCiQ000000000000US",
    panBin: "518600",
    panLastFour: "8785",
    digitalCardData: {
      descriptorName: "Mastercard",
      artUri:
        "https://sbx.assets.mastercard.com/card-art/combined-image-asset/HIGH-MASK-3x.png",
      isCoBranded: false,
      status: "ACTIVE",
    },
    digitalCardFeatures: [],
    panExpirationMonth: "11",
    panExpirationYear: "2030",
    paymentCardDescriptor: "mastercard",
    paymentCardType: "PREPAID",
    maskedBillingAddress: {
      line1: "6*** S**** S********* D****",
      city: "Los Angeles",
      state: "CA",
      countryCode: "US",
      zip: "90056",
    },
    cardholderFirstName: "a*******",
    cardholderLastName: "c********",
    cardholderFullName: "a******* c********",
  },
  {
    srcDigitalCardId: "IEkvU4PJSpaldBJ818Jssg000000000000US",
    panBin: "512035",
    panLastFour: "4537",
    digitalCardData: {
      descriptorName: "MasterCard Test Bank",
      artUri:
        "https://sbx.assets.mastercard.com/card-art/combined-image-asset/6713d73d-a701-4bd2-bc9b-2e98940de9c7.png",
      coBrandedName: "test co-brand",
      isCoBranded: true,
      status: "ACTIVE",
    },
    digitalCardFeatures: [],
    panExpirationMonth: "01",
    panExpirationYear: "2039",
    paymentCardDescriptor: "mastercard",
    paymentCardType: "CREDIT",
    maskedBillingAddress: {
      line1: "6*** S**** S********* D****",
      city: "Los Angeles",
      state: "CA",
      countryCode: "US",
      zip: "90056",
    },
    cardholderFirstName: "a*******",
    cardholderLastName: "c********",
    cardholderFullName: "a******* c********",
  },
];

let Visa = [
  {
    dateOfCardCreated: "2025-02-04T10:08:16.195Z",
    dateOfCardLastUsed: "2025-02-06T08:24:39.995Z",
    digitalCardData: {
      artHeight: 210,
      artUri:
        "https://sandbox.assets.vims.visa.com/vims/cardart/5af3734cca4e439e97f00e4474d82447_imageA@2x.png",
      artWidth: 334,
      authenticationMethods: [],
      descriptorName: "OBN",
      pendingEvents: [],
      status: "ACTIVE",
    },
    maskedBillingAddress: {
      addressId: "f4fd866d-e42d-5142-8521-14eab5191802",
      name: null,
      line1: "105*****",
      line2: null,
      line3: null,
      city: "*****",
      state: "CA",
      zip: "*****",
      countryCode: "US",
    },
    panBin: "439584",
    panExpirationMonth: "12",
    panExpirationYear: "2025",
    panLastFour: "0110",
    paymentAccountReference: "V0010013024130443242789298470",
    paymentCardType: "DEBIT",
    srcDigitalCardId: "269c9e27-893b-6bcf-87ee-157d36eb4d02",
  },
  {
    countryCode: "US",
    dateOfCardCreated: "2025-01-31T13:24:58.034Z",
    dateOfCardLastUsed: "2025-02-03T12:46:50.551Z",
    dcf: {
      logoUri: "http://mastercard.com/",
      name: "mastercard",
      uri: "https://sandbox.src.mastercard.com/pay/",
    },
    digitalCardData: {
      artUri:
        "https://sbx.assets.mastercard.com/card-art/combined-image-asset/42d31eae-9961-45b6-9fe3-76ad70a0a525.png",
      authenticationMethods: [
        {
          authenticationMethodType: "FIDO2",
        },
      ],
      descriptorName: "Test Bank 2",
      presentationName: "",
      status: "ACTIVE",
    },
    digitalCardFeatures: {},
    maskedBillingAddress: {
      name: "Ab*****k Ch******a",
      line1: "6*** S**** S********* D****",
      city: "Los Angeles",
      state: "CA",
      countryCode: "US",
      zip: "90056",
      addressId: "7566af71-6543-4064-87a3-597aab52076f",
    },
    panBin: "222300",
    panExpirationMonth: "03",
    panExpirationYear: "2030",
    panLastFour: "4586",
    paymentCardDescriptor: "mastercard",
    paymentCardType: "DEBIT",
    srcDigitalCardId: "WMXp_LfbQm66KhWMdslcqw000000000000US",
    tokenLastFour: "7922",
  },
  {
    countryCode: "US",
    dateOfCardCreated: "2024-12-23T07:37:09.694Z",
    dateOfCardLastUsed: "2025-02-03T12:40:18.722Z",
    dcf: {
      logoUri: "http://mastercard.com/",
      name: "mastercard",
      uri: "https://sandbox.src.mastercard.com/pay/",
    },
    digitalCardData: {
      artUri:
        "https://sbx.assets.mastercard.com/card-art/combined-image-asset/HIGH-MASK-3x.png",
      authenticationMethods: [
        {
          authenticationMethodType: "FIDO2",
        },
      ],
      descriptorName: "",
      presentationName: "",
      status: "ACTIVE",
    },
    digitalCardFeatures: {},
    maskedBillingAddress: {
      name: "T*** Ma*******d",
      line1: "6*** S**** S********* D****",
      city: "Los Angeles",
      state: "CA",
      countryCode: "US",
      zip: "90056",
      addressId: "4243fea9-a531-467c-bcb1-d5c93fddc6d0",
    },
    panBin: "518600",
    panExpirationMonth: "01",
    panExpirationYear: "2039",
    panLastFour: "9908",
    paymentCardDescriptor: "mastercard",
    paymentCardType: "PREPAID",
    srcDigitalCardId: "geHXpeEfQF256Qs4Fdamvg000000000000US",
  },
  {
    countryCode: "US",
    dateOfCardCreated: "2025-01-02T08:35:08.378Z",
    dateOfCardLastUsed: "2025-02-03T12:37:27.356Z",
    dcf: {
      logoUri: "http://mastercard.com/",
      name: "mastercard",
      uri: "https://sandbox.src.mastercard.com/pay/",
    },
    digitalCardData: {
      artUri:
        "https://sbx.assets.mastercard.com/card-art/combined-image-asset/HIGH-MASK-3x.png",
      authenticationMethods: [
        {
          authenticationMethodType: "FIDO2",
        },
      ],
      descriptorName: "",
      presentationName: "",
      status: "ACTIVE",
    },
    digitalCardFeatures: {},
    maskedBillingAddress: {
      name: "Ab*****k Ch******a",
      line1: "6*** S**** S********* D****",
      city: "Los Angeles",
      state: "CA",
      countryCode: "US",
      zip: "90056",
      addressId: "41b170e9-26b6-42dc-94d2-567c4d7edc21",
    },
    panBin: "518600",
    panExpirationMonth: "11",
    panExpirationYear: "2030",
    panLastFour: "8785",
    paymentCardDescriptor: "mastercard",
    paymentCardType: "PREPAID",
    srcDigitalCardId: "uCwj2iwDR0izPxOQuJHCiQ000000000000US",
  },
  {
    countryCode: "US",
    dateOfCardCreated: "2024-12-23T07:23:31.173Z",
    dateOfCardLastUsed: "2025-02-03T07:00:39.747Z",
    dcf: {
      logoUri: "http://mastercard.com/",
      name: "mastercard",
      uri: "https://sandbox.src.mastercard.com/pay/",
    },
    digitalCardData: {
      artUri:
        "https://sbx.assets.mastercard.com/card-art/combined-image-asset/6713d73d-a701-4bd2-bc9b-2e98940de9c7.png",
      authenticationMethods: [
        {
          authenticationMethodType: "FIDO2",
        },
      ],
      descriptorName: "MasterCard Test Bank",
      presentationName: "",
      status: "ACTIVE",
    },
    digitalCardFeatures: {},
    maskedBillingAddress: {
      name: "T*** Ma*******d",
      line1: "6*** S**** S********* D****",
      city: "Los Angeles",
      state: "CA",
      countryCode: "US",
      zip: "90056",
      addressId: "67fd5256-c7cf-4f17-8f21-3bcaaa4e885a",
    },
    panBin: "512035",
    panExpirationMonth: "01",
    panExpirationYear: "2039",
    panLastFour: "4537",
    paymentCardDescriptor: "mastercard",
    paymentCardType: "CREDIT",
    srcDigitalCardId: "IEkvU4PJSpaldBJ818Jssg000000000000US",
    tokenLastFour: "4489",
  },
];
